language: rust

before_install:
  - curl -L https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.1/mdbook-v0.2.1-x86_64-unknown-linux-musl.tar.gz | tar xzf -
  - export PATH=$PATH:`pwd`
  - bundler install

script:
  - ./ci/build.sh

deploy:
  provider: script
  script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd _site && ../rust_out)
  skip_cleanup: true
  on:
    branch: master
