trigger:
  - master

jobs:
  - job: publish
    steps:
      - bash: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.prependpath]$HOME/.cargo/bin"
        displayName: Install rust
      - script: |
          set -e
          curl -L https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.1/mdbook-v0.2.1-x86_64-unknown-linux-musl.tar.gz | tar xzf -
          echo "##vso[task.prependpath]$PWD"
        displayName: Install mdbook
      - script: bundler install
        displayName: Install ruby deps
      - script: ./ci/build.sh
        displayName: Build site
      - script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd _site && ../rust_out)
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          GITHUB_DEPLOY_KEY: $(GITHUB_DEPLOY_KEY)
